#use_frameworks!

platform :ios, '9.0'

install! 'cocoapods', :disable_input_output_paths => true

target 'HKPhotoTools_Example' do
  pod 'HKPhotoTools', :path => '../'

  target 'HKPhotoTools_Tests' do
    inherit! :search_paths

    pod 'Kiwi'
    pod 'FBSnapshotTestCase'
  end
end
